### ISSUE TITLE
ToDO

### ISSUE THREAD

**Issue by Its-Just-Nans** [Its-Just-Nans/bandwidth-calculator#1]
- [x] bandwidth unit should be displayed like
  * 1 bit per sec (bps)
  * 10 Mebibytes per second (MiBps)
- [x] automatic calculation when an unit is changed
- [x] automatic calculation when a value is entered in any input section (when Enter pressed)
